USE [单位房产管理系统]
GO

/****** Object:  Table [dbo].[Secret]    Script Date: 2016/6/30 13:00:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Secret](
	[Wno] [char](8) NOT NULL,
	[secret] [char](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[Wno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

